Hsc 78 Config
servacc/CVSPipeline pull request #1
Opened 2021-02-24 10:46 UTC by efimov-evgeniy

2021-03-02 07:22 UTC, ssysoenko requested changes
Добавь, пожалуйста, тест с примером использования.

2021-03-02 07:22 UTC, ssysoenko commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.18)
Почему?

2021-03-02 10:04 UTC, efimov-evgeniy commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.18)
Зачем нам увеличивать требования для cmake? Нужно наоборот выставить минимум

2021-03-02 15:53 UTC, ssysoenko commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.18)
Почему нужен минимум?

2021-03-02 16:06 UTC, ssysoenko commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.18)
Добавлю.
На какой-то конфе выступал гражданин который про себя говорил, что много и больно возился с cmake. Он сказал - желательно, чтобы версия cmake указананная и фактическая - соответствовали. У него были проблемы из-за расхождения версий (т.е. новая бажила на страом cmakelists и работала если поднять версию в  cmakelists). Во всяком случае мне так запомнилось.
Ну и выколупывать из cmake когда какая фича добавилась - вот совсем не хочется (просто понизив версию в файле нельзя, вроде. Надо подымать историю изменений по версиям).
Это библиотека. Очень надеюсь, что изменяться она будет категорически редко. А это значит, что версия cmake  должна устареть. Ради исправления пары цифирь версии в код полезет только воистину отчаянный человек (если не будет какого-либо бага). Так что можно смело ставить последнюю из тех что есть.
З.ы. В rc2 весит версия 3.20. Так что 3.19 может стать не самой новой за время реквеста. Ну и cmake довольно часто обновляется. Версия за полгода-год устареет на 2-3 минора.

2021-03-02 20:35 UTC, efimov-evgeniy commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.18)
>  У него были проблемы из-за расхождения версий

Звучит сомнительно, потому что по логике указываемая версия - просто значение для проверки.

> Почему нужен минимум?

А зачем поднимать версию, если текущая работает? На ubuntu 20.04 lts стоит cmake 3.16. То есть, например, для тестирования и сборки в докере придётся тащить ешё cmake. Зачем? Чего мы добьёмся увеличив версию?
Про "выколупывать" и "понизив версию ... нельзя" не понял.

2021-03-03 06:28 UTC, ssysoenko commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.18)
Ну вроде как это не тот случай когда старое лучше нового. 
В таком случае почему 3.18, а не 3.16?
Дык докер он вроде и существует для настройки окружения без ручных манипуляций. 1 раз прописал и радуйся.

В целом аргумент про дефолтную в пакетах убунты мне кажется убедительным. Поэтому если и понижать - то до 3.16 (если, конечно, продолжит работать).

2021-03-03 06:29 UTC, ssysoenko requested changes
Не соответствует стилю.

2021-03-03 06:29 UTC, ssysoenko commented on pipeline/include/cvs/config/config.h
> +  [[nodiscard]] const std::string_view get_name() const;
Мы не договорились о snake_case. Вот когда и если договоримся - будем писать так!

2021-03-03 06:59 UTC, ssysoenko requested changes
Может нам переместить конфиг в либу common? Подозреваю, что в какой-то момент common может стать отдельным репо.

2021-03-03 10:07 UTC, efimov-evgeniy commented on pipeline/include/cvs/config/config.h
> +  [[nodiscard]] const std::string_view get_name() const;
По привычке. Исправлю перед мёржем

2021-03-04 10:07 UTC, Aldrog requested changes

2021-03-04 10:07 UTC, Aldrog commented on pipeline/include/cvs/config/config_utils.hpp
> +constexpr auto get_name(const char (&string)[string_size]) {
Почему такая странная конструкция? Вроде никакого смысла делать string ссылкой нет.

2021-03-04 10:07 UTC, Aldrog commented on pipeline/include/cvs/config/config_utils.hpp
> +template <class Type, bool is_optional = false>
Почему используется то `class`, то `typename`? У нас в code style вроде этот момент не описан, но я предлагаю везде писать `typename`, как более однозначный и не вызывающий лишних ассоциаций термин.

2021-03-04 10:07 UTC, Aldrog commented on pipeline/include/cvs/config/config_utils.hpp
> +constexpr size_t length(const char *str) {
Было бы хорошо сделать эту функцию `consteval`, чтобы случайно не вызвать в рантайме.

2021-03-04 10:07 UTC, Aldrog commented on pipeline/include/cvs/config/config_utils.hpp
> +constexpr size_t length(const char *str) {
Вроде уже GCC 10 достаточно хорошо поддерживает `consteval` для этого случая.

2021-03-04 10:07 UTC, Aldrog commented on pipeline/include/cvs/config/config_base.hpp
> +#define Object(object_name, ...) Object_base(object_name, false, __VA_ARGS__)
Предлагаю
1. Имена макросов писать капсом
2. Называть их длинно и явно (CONFIG_OBJECT, CONFIG_VALUE, DECLARE_CONFIG etc.)
3. Вспомогательным макросам добавить какой-нибудь префикс/суффикс, чтобы они не смешивались и не использовались по ошибке.

2021-03-04 10:16 UTC, efimov-evgeniy commented on pipeline/include/cvs/config/config_utils.hpp
> +constexpr auto get_name(const char (&string)[string_size]) {
Без ссылки он не сможет аргумент шаблона вывести - couldn’t deduce template parameter ‘string_size’.

2021-03-04 10:17 UTC, efimov-evgeniy commented on pipeline/include/cvs/config/config_utils.hpp
> +template <class Type, bool is_optional = false>
Честно говоря, ставил как придётся. Поправлю на typename

2021-03-04 10:19 UTC, efimov-evgeniy commented on pipeline/include/cvs/config/config_utils.hpp
> +constexpr size_t length(const char *str) {
В 20.04 LTS по умолчанию GCC 9. Компилиться с 10-ым я не решился, потому что по-хорошему мне нужен 11 =)
Мы всё-таки либу делаем, а если либа компилиться только на последних компиляторах, то имхо это не очень правильно.

2021-03-04 10:19 UTC, efimov-evgeniy commented on pipeline/include/cvs/config/config_base.hpp
> +#define Object(object_name, ...) Object_base(object_name, false, __VA_ARGS__)
Сыглы, поправлю

2021-03-04 11:58 UTC, Aldrog commented on pipeline/include/cvs/config/config_utils.hpp
> +constexpr size_t length(const char *str) {
> Мы всё-таки либу делаем, а если либа компилиться только на последних компиляторах, то имхо это не очень правильно.

Зависит от назначения. Вообще, если мы хотим поддерживать сборку не самыми свежими компиляторами, нельзя было C++20 ставить.

2021-03-04 17:42 UTC, ssysoenko commented on pipeline/include/cvs/config/config_utils.hpp
> +constexpr size_t length(const char *str) {
> Мы всё-таки либу делаем, а если либа компилиться только на последних компиляторах, то имхо это не очень правильно.
А почему не правильно? Есть ограничения по используемым фичам. Нафига жестить то?

2021-03-04 18:53 UTC, efimov-evgeniy commented on pipeline/include/cvs/config/config_utils.hpp
> +constexpr size_t length(const char *str) {
Не понял что значит "жестить" и какие ограничения.

2021-03-09 16:26 UTC, shkryab requested changes

2021-03-09 16:26 UTC, shkryab commented on pipeline/include/cvs/config/config.h
> +  [[nodiscard]] bool has_value() const;
snake_case

2021-03-09 19:01 UTC, efimov-evgeniy commented on pipeline/include/cvs/config/config.h
> +  [[nodiscard]] bool has_value() const;
Потому что косим под std::optional

2021-03-10 13:27 UTC, Aldrog commented on pipeline/include/cvs/config/config.h
> +  std::string _key;
Мы разве не в конце `_` добавляем, в соответствии с [Google Style Guide](https://google.github.io/styleguide/cppguide.html#Variable_Names)?

2021-03-15 20:36 UTC, ssysoenko requested changes

2021-03-15 20:36 UTC, ssysoenko commented on pipeline/include/cvs/config/config.h
> +  [[nodiscard]] bool has_value() const;
Ну дык это же не оно.

2021-03-15 20:36 UTC, ssysoenko commented on pipeline/include/cvs/config/config.h
> +
namespace

2021-03-15 20:36 UTC, ssysoenko commented on pipeline/include/cvs/config/config_base.hpp
> +    Config_static_type_##name ::ResultType name##_;                                                               \
Думаю, в даннос случае постфикс/префикс "_" или какой другой совсем не в тему. Поле по итогу названо не так как задано при определении в макросах.

Да и вообще если уж какие префиксы суфиксы - чо не венгерская нотация? Сильно информативнее.

По мне так от всяких суфиксов лучше отказаться совсем и использовать только в случае когда не получается выдумать имя переменной не совпадающее с методом и т.п.

2021-03-15 22:23 UTC, efimov-evgeniy commented on pipeline/include/cvs/config/config.h
> +  [[nodiscard]] bool has_value() const;
Что не оно?

2021-03-16 09:21 UTC, Aldrog commented on pipeline/include/cvs/config/config.h
> +  [[nodiscard]] bool has_value() const;
Я правильно понимаю, что `Config` где-то передаётся в шаблонную функцию, работающую также и с `optional`?

Вообще, кажется странным, что `Config::make` возвращает `std::optional<Config>`, но при этом сам `Config` тоже может быть пустым.

2021-03-16 09:45 UTC, Aldrog commented on pipeline/include/cvs/config/config_base.hpp
> +    Config_static_type_##name ::ResultType name##_;                                                               \
> Да и вообще если уж какие префиксы суфиксы - чо не венгерская нотация? Сильно информативнее.
>
> По мне так от всяких суфиксов лучше отказаться совсем и использовать только в случае когда не получается выдумать имя переменной не совпадающее с методом и т.п.

Но style guide у нас ссылается на вот это: https://google.github.io/styleguide/cppguide.html#Naming

Так-то я тоже считаю, что все эти префиксы-суффиксы излишни и вполне достаточно было бы разделять в стиле типы от всего остального (отдельные стили для функций и переменных мне уже не нравится, т.к. функторы тогда выглядят как переменные, а используются как функции).

2021-03-16 10:07 UTC, efimov-evgeniy commented on pipeline/include/cvs/config/config.h
> +  [[nodiscard]] bool has_value() const;
Если из `make` вернулся `nullopt`, это значит, что не смогли считать или распарсить файл. А сам `Config` - по сути простая обёртка на `ptree`. 

> Я правильно понимаю, что Config где-то передаётся в шаблонную функцию, работающую также и с optional?

Да. Можно сделать что-то вроде обёртки чтобы скрыть такое имя функции, но я сомневаюсь, что усложнять код ради соответствия правилам именования логично.

2021-03-31 09:26 UTC, closed without merging