Feature/lib cvs common update
servacc/CVSPipeline pull request #10
Opened 2021-10-19 12:22 UTC by ssysoenko

Обновление для ПР https://github.com/servacc/CVSCommon/pull/13

2021-10-19 13:09 UTC, efimov-evgeniy approved these changes, later dismissed

2021-10-25 03:18 UTC, efimov-evgeniy requested changes

2021-10-25 03:18 UTC, efimov-evgeniy commented on pipeline/include/cvs/pipeline/tbb/tbbContinueNode.hpp
> +               beforeProcessing();
Не совсем понимаю: этот метод от какого объекта вызывается? Свободных функций с таким именем, вроде, нет.
И может RAII?

2021-10-25 03:18 UTC, efimov-evgeniy commented on pipeline/include/cvs/pipeline/registrationHelper.hpp
> +        // fix warning
Так и планировалось?

2021-10-25 07:14 UTC, ssysoenko commented on pipeline/include/cvs/pipeline/tbb/tbbContinueNode.hpp
> +               beforeProcessing();
Всмысле явно написать `this->`?
Для чего и как тут RAII применять?

2021-10-25 07:18 UTC, ssysoenko commented on pipeline/include/cvs/pipeline/registrationHelper.hpp
> +        // fix warning
Этот ретурн никогда не выполняется. Точнее не должен.

2021-10-25 10:27 UTC, efimov-evgeniy commented on pipeline/include/cvs/pipeline/registrationHelper.hpp
> +        // fix warning
Ну я о том, чтобы вывести предупреждение в этом случае

2021-10-25 10:30 UTC, efimov-evgeniy commented on pipeline/include/cvs/pipeline/tbb/tbbContinueNode.hpp
> +               beforeProcessing();
А, прозевал наследование.
Как я понял, ты обозначаешь границы некоторого интервала, так что логично было бы ограничивать это дело скоупом. Но это не критично

2021-10-25 15:04 UTC, ssysoenko commented on pipeline/include/cvs/pipeline/registrationHelper.hpp
> +        // fix warning
Туда вообще попадать не должно. Сверху в любом случае случиться исключение. return поставлен чтобы компилятор варнингом не сыпал

2021-10-25 15:43 UTC, efimov-evgeniy approved these changes

2021-10-25 17:04 UTC, merged