Feature/throw with nested
servacc/CVSPipeline pull request #12
Opened 2021-11-17 09:02 UTC by ssysoenko

Добавлены вложенные исключения с обозначением ноды.
Исправлена бага с инфо сорцноды
Добавлено логирование входа и выхода из ноды

2021-11-18 22:50 UTC, efimov-evgeniy requested changes

2021-11-18 22:50 UTC, efimov-evgeniy commented on pipeline/include/cvs/pipeline/tbb/tbbContinueNode.hpp
> +                 return result;
Я бы предложил вынести `return` за `try ... catch` чтобы не ловить в случае чего ошибки не вызова `return`. Ну и компилятор не будет варнингами сыпать.

2021-11-20 08:43 UTC, ssysoenko commented on pipeline/include/cvs/pipeline/tbb/tbbContinueNode.hpp
> +                 return result;
Это накладывает на тип ограничение. Нужен будет конструктор без параметров. Имхо для либы делать подобные ограничения не хорошо

2021-11-21 12:29 UTC, efimov-evgeniy approved these changes

2021-11-21 12:32 UTC, merged