HSC-79 Module interface
servacc/CVSPipeline pull request #2
Opened 2021-03-01 16:19 UTC by Aldrog

2021-03-02 07:31 UTC, ssysoenko submitted a review, later dismissed

2021-03-03 10:06 UTC, efimov-evgeniy requested changes

2021-03-03 10:06 UTC, efimov-evgeniy commented on pipeline/src/pipeline/imodule.cpp
> +  }
Я бы строчку пропустил, чтобы один if от другого отделить.

2021-03-03 10:06 UTC, efimov-evgeniy commented on test/main.cpp
> +                                 boost::dll::load_mode::rtld_global | boost::dll::load_mode::rtld_lazy};
Имхо тут надо либо пропустить строку, либо перенести аргументы конструктора lib на новую строку, либо убрать выравнивание. Текуший вариант выглядит вырвиглазно.

2021-03-03 10:06 UTC, efimov-evgeniy commented on pipeline/include/cvs/pipeline/imodule.hpp
> +using IModuleDestructor  = void(IModule *);
А нам нужен деструктор у модуля?

2021-03-03 10:34 UTC, Aldrog commented on pipeline/include/cvs/pipeline/imodule.hpp
> +using IModuleDestructor  = void(IModule *);
Возможно, было бы лучше их назвать Creator и Deleter. Ниже в `REGISTER_MODULE` описаны стандартные определения.

2021-03-03 10:44 UTC, Aldrog commented on test/main.cpp
> +                                 boost::dll::load_mode::rtld_global | boost::dll::load_mode::rtld_lazy};
Если ты про следующую строку, то я за то, чтобы отключить выравнивание. Оно не только в этом месте код нечитабельным делает — объявления функций тоже ужасно с ним выглядят, а расставлять везде пустые строки через одну как-то странно.

2021-03-03 11:21 UTC, efimov-evgeniy commented on test/main.cpp
> +                                 boost::dll::load_mode::rtld_global | boost::dll::load_mode::rtld_lazy};
Да, но пока не отключили, можно исправить малой кровью.
По поводу пропуска строк: после блоков (например, if) имхо стоит пропускать, если после не идёт закрывающая скобка внешнего блока.

2021-03-03 14:05 UTC, Aldrog commented on pipeline/src/pipeline/imodule.cpp
> +  }
Следующие два if не стал разделять, они короткие и практически одно и то же делают.

2021-03-03 16:27 UTC, efimov-evgeniy approved these changes

2021-03-04 07:13 UTC, ssysoenko approved these changes

2021-03-04 17:37 UTC, merged