I element invalid instantiation static assert
servacc/CVSPipeline pull request #5
Opened 2021-06-16 10:00 UTC by efimov-evgeniy

Добавлен static_assert для информативной ошибки в случае некорректных аргументов шаблона IElement (IElementPtr), мелкие правки

2021-06-16 10:08 UTC, ssysoenko commented on pipeline/include/cvs/pipeline/ielement.hpp
> +
Чот я забыл. Зачем именно нужен этот прокси?

2021-06-16 10:08 UTC, ssysoenko commented on pipeline/src/pipeline/imodule.cpp
> +  const auto delete_module      = &lib.get<detail::IModuleDeleter>("deleteModule");
Может отделить это от общего блока раз это функция, а не ее результат?

2021-06-16 10:34 UTC, Aldrog requested changes

2021-06-16 10:34 UTC, Aldrog commented on pipeline/src/pipeline/imodule.cpp
> +  const auto new_module    = lib.get<detail::IModuleCreator>("newModule")();
Наверное не стоит вызывать `newModule()` до проверки версии пайплайна.

2021-06-16 10:34 UTC, Aldrog commented on pipeline/include/cvs/pipeline/ielement.hpp
> +};
Этот прокси нужен исключительно для того, чтобы в сообщении об ошибке видеть `IElementPtr` вместо `IElement`? Может, и без этого достаточно понятно?

2021-06-16 10:34 UTC, Aldrog commented on pipeline/include/cvs/pipeline/ielement.hpp
> +  static_assert(std::is_invocable<Signature>::value, "IElement template argument must be function type");
Тут некорректно `is_invocable` используется. Он выдаст `false` на абсолютно корректное значение (но мы этого не увидим, потому что выберется другая инстанциация), и `true` на какой-нибудь `std::function<void()>` (что приведёт к менее читаемым ошибкам).

Думаю, лучше использовать здесь выражение, всегда вычисляющееся в `false`, например `sizeof(Signature) < 0`.

2021-06-16 10:55 UTC, efimov-evgeniy commented on pipeline/include/cvs/pipeline/ielement.hpp
> +};
Нет, прокси нужен для того, чтобы запретить объявление указателей с некорректным аргументом шаблона

2021-06-16 10:55 UTC, efimov-evgeniy commented on pipeline/include/cvs/pipeline/ielement.hpp
> +
https://github.com/servacc/CVSPipeline/pull/5#discussion_r652577674

2021-06-16 10:58 UTC, efimov-evgeniy commented on pipeline/include/cvs/pipeline/ielement.hpp
> +  static_assert(std::is_invocable<Signature>::value, "IElement template argument must be function type");
> на какой-нибудь `std::function<void()>`
Это должна забрать на себя специализация. Но, в принципе, согласен.

2021-06-16 11:09 UTC, Aldrog commented on pipeline/include/cvs/pipeline/ielement.hpp
> +};
А, понял, без него ошибка только на инициализацию вылезет. Тогда только замечание относительно `is_invocable` к нему тоже относится.

2021-06-16 11:12 UTC, Aldrog approved these changes

2021-06-29 09:38 UTC, ssysoenko approved these changes

2021-06-29 09:53 UTC, merged