Feature/gui
servacc/CVSPipeline pull request #6
Opened 2021-07-04 10:53 UTC by ssysoenko

Добавлен класс для взаимодействия со входом/выходом пайплайна. Взаимодействие происходит через интерфейс IView. Есть реализация для tbb. Это пока первый вариант который надо будет переделать:

- спрятать tbb (сейчас необходимо явно наследоваться от TbbView. Нужен вариант с разделением по типу IElement и IExecutionNode)
- данные из пайплайна необходимо не вручную проверять, а получать как эвенты (такую реализацию пробовал, но там нужно много писать, сейчас нет времени на это)

Добавлены буферезирующие ноды.

Суть взаимодействия с пайплайном:
Определяется класс наследник IView имеющий вхорды и выходы. Входы и выходы подключаются к нодам пайплайна. Вся работа происходит в методе `IView::exec` который выполняется в отдельном от пайплайна потоке (в потоке main). Взаимодействие с входами/выходами происходит через `tryGet<>()`/`tryPut<>()` методы.

2021-07-14 13:51 UTC, Aldrog submitted a review, later dismissed

2021-07-20 00:47 UTC, efimov-evgeniy requested changes

2021-07-20 00:47 UTC, efimov-evgeniy commented on libmain/src/main.cpp
> +  auto pipeline_cfg  = config.getFirstChild("Pipeline").value();
Предлагаю уже до чего-нибудь договориться. Либо мы проверяем значения, либо пишем вспомогательные функции. Так оставлять считаю вредным

2021-07-20 00:47 UTC, efimov-evgeniy commented on pipeline/src/pipeline/pipeline.cpp
> +void Pipeline::initPipeline(Pipeline &                                  pipeline,
Почему это происходит в отдельной функции, а не в конструкторе/make() ?

2021-07-20 00:47 UTC, efimov-evgeniy commented on pipeline/include/cvs/pipeline/tbb/tbbBufferTemplateNode.hpp
> +  bool connect(std::any sndr, std::size_t i) override {
> sndr

Какая-то странная попытка сократить))

2021-07-20 00:47 UTC, efimov-evgeniy commented on pipeline/include/cvs/pipeline/tbb/tbbBufferTemplateNode.hpp
> +    if (i == 0) {
Почему бы не объединить условия?

2021-07-20 00:47 UTC, efimov-evgeniy commented on pipeline/include/cvs/pipeline/tbb/tbbBufferTemplateNode.hpp
> +        ::tbb::flow::sender<T>* s = std::any_cast<::tbb::flow::sender<T>*>(sndr);
Нужно бы избавиться от `any_cast`, которые не обёрнуты в try-catch

2021-07-20 00:47 UTC, efimov-evgeniy commented on pipeline/include/cvs/pipeline/tbb/tbbView.hpp
> +    if (std::get<I>(inputs))
Лучше инвертировать

2021-07-20 00:47 UTC, efimov-evgeniy commented on pipeline/include/cvs/pipeline/tbb/tbbcontinuenode.hpp
> +      if (typeid(::tbb::flow::sender<::tbb::flow::continue_msg>*) == sndr.type()) {
Объединить

2021-07-20 00:47 UTC, efimov-evgeniy commented on pipeline/include/cvs/pipeline/tbb/tbbfunctionnode.hpp
> +    if constexpr (1 < std::tuple_size_v<std::tuple<Args...>>) {
А зачем эта правка?

2021-07-20 00:47 UTC, efimov-evgeniy commented on pipeline/include/cvs/pipeline/tbb/tbbfunctionnode.hpp
> +    if (typeid(::tbb::flow::sender<ArgumentsType>*) == sndr.type()) {
Инвертировать

2021-07-20 00:47 UTC, efimov-evgeniy commented on pipeline/include/cvs/pipeline/tbb/tbbjoinnode.hpp
>      if (I == i) {
Можно инвертировать

2021-07-20 00:47 UTC, efimov-evgeniy commented on pipeline/include/cvs/pipeline/tbb/tbbsplitnode.hpp
> +      if (typeid(::tbb::flow::sender<ResultType>*) == sndr.type()) {
Объединить

2021-07-20 00:47 UTC, efimov-evgeniy commented on pipeline/src/pipeline/registrationhelper.cpp
>    std::string module_manager_key = "Default";
Судя по всему, эти строки стоит сделать константными

2021-07-20 06:17 UTC, ssysoenko commented on pipeline/src/pipeline/pipeline.cpp
> +void Pipeline::initPipeline(Pipeline &                                  pipeline,
Для наследования от `Pipeline` и последующем переписывании процесса конфигурации, если требуется.

2021-07-20 06:19 UTC, ssysoenko commented on libmain/src/main.cpp
> +  auto pipeline_cfg  = config.getFirstChild("Pipeline").value();
Так мы договорились. Нужно дописывать конфиг. Текущий вариант с оберткой, имхо, не подходит. Нужен `expected` или его аналог.

2021-08-09 16:01 UTC, ssysoenko commented on pipeline/include/cvs/pipeline/tbb/tbbfunctionnode.hpp
> +    if constexpr (1 < std::tuple_size_v<std::tuple<Args...>>) {
У меня стилизатор сума сходил на этих скобочках.

2021-08-10 10:29 UTC, ssysoenko commented on pipeline/include/cvs/pipeline/tbb/tbbBufferTemplateNode.hpp
> +    if (i == 0) {
ИМХО если объеденить - будет длинное условие которое сложно воспринимать. А так несколько покороче которые легче читаются.

2021-08-10 10:31 UTC, ssysoenko commented on pipeline/include/cvs/pipeline/tbb/tbbBufferTemplateNode.hpp
> +        ::tbb::flow::sender<T>* s = std::any_cast<::tbb::flow::sender<T>*>(sndr);
А там может выскочить что-то что не проверятеся условием выше?
Вообще нужно интегрировать expected и пересматривать сигнатуру. Но это потом. Не в этом PR

2021-08-10 10:32 UTC, ssysoenko commented on pipeline/include/cvs/pipeline/tbb/tbbView.hpp
> +    if (std::get<I>(inputs))
Чем лучше?

2021-08-30 15:38 UTC, Aldrog approved these changes
В ряде мест можно было бы инвертировать ветки if-else, чтобы if были более короткими (Женя на это уже указывал), но это не критично.

2021-08-30 15:49 UTC, efimov-evgeniy approved these changes

2021-08-30 15:51 UTC, merged